### ISSUE TITLE
extern fn CInt win32_WSACleanup() @extern("WSACleanup") @if(env::WIN32)

### ISSUE THREAD

**Issue by LukyGuyLucky** [velikoss/c3-api#1]
It failed during compiling ,and then I added the above subjected line ,now it compiles.

But when I run the main program c3api.exe,it crashed after below message:

```
Env is Win32
WinSock Log:                 WinSock 2.0

                    Running

WSA started successfully
listening on <127.0.0.1:8080>
```

win10 64 bit,under common console cmd.exe ,and also tried under Visual Studio 2019 x64 Native Commandline window.

**Comment by velikoss** [comment]
Can you give more information about C3C version that you are using and what line did you change?

**Comment by LukyGuyLucky** [comment]
> Can you give more information about C3C version that you are using and what line did you change?
Thank you for taking time to look at this.

c3c version: 0.6.2(prerelease)

```
extern fn CInt win32_WSAGetLastError() @extern("WSAGetLastError") @if(env::WIN32);
extern fn CInt win32_WSACleanup() @extern("WSACleanup") @if(env::WIN32);//---->added this line.

```

**Comment by velikoss** [comment]
Use the latest version of the compiler from Github repo

**Comment by LukyGuyLucky** [comment]
> Use the latest version of the compiler from Github repo

Yes,that's the day before yesterday ~ yesterday pre-release version.

**Comment by velikoss** [comment]
> > Can you give more information about C3C version that you are using and what line did you change?
> > Thank you for taking time to look at this.
> 
> c3c version: 0.6.2(prerelease)
> 
> ```
> extern fn CInt win32_WSAGetLastError() @extern("WSAGetLastError") @if(env::WIN32);
> extern fn CInt win32_WSACleanup() @extern("WSACleanup") @if(env::WIN32);//---->added this line.
> ```

Strange. it doesn't need that function in the code itself because of https://github.com/c3lang/c3c/pull/1317

**Comment by velikoss** [comment]
Fixed it in https://github.com/velikoss/c3-api/commit/954af939c35411b3110f96227889181a5a3369ab
Could you try that?

**Comment by LukyGuyLucky** [comment]
> Fixed it in [954af93](https://github.com/velikoss/c3-api/commit/954af939c35411b3110f96227889181a5a3369ab) Could you try that?

It runs successfully.
Thank you for the prompt help.

**Comment by LukyGuyLucky** [comment]
Just noticed although I've closed the running window and also 127.0.0.1:8080 Edge Window,c3api.exe is still living in the Task Manager Window.Is this normal？

**Comment by velikoss** [comment]
Actually, no. I'll look into it

**Comment by velikoss** [comment]
Can you specify how you're running the program?

**Comment by velikoss** [comment]
Ping @LukyGuyLucky

**Comment by LukyGuyLucky** [comment]
Sure.

But I can't reproduce the issue today.

It is like this:
``` 
cd c3-api
c3c compile-run .
cd build
c3-api.exe
```
it is running in the windows console and output below information:
```
Env is Win32
WinSock Log:                 WinSock 2.0

                    Running

WSA started successfully
listening on <127.0.0.1:8080>
```
Now I was opening Chrome,entering 127.0.0.1:8080
it shows below:
```
{"type":"error","status":404}
```
Close Chrome 

Close windows console

Now open Windows Task Manager window,the c3-api.exe is (not) still there.

Thank you for taking time to look at this issue.Thank you!

**Comment by velikoss** [comment]
compile-run automatically launches builded program. Use only compile and only then c3-api.exe

**Comment by LukyGuyLucky** [comment]
Thank you!
